### ISSUE TITLE
Don't upload release candidates to the main label

### ISSUE THREAD

**Issue by xhochy** [conda-forge/marshmallow-feedstock#40]
You can upload release candidates on conda-forge but please use a special label like `marshmallow-rc` as documented in https://conda-forge.org/docs/maintainer/conda_forge_yml.html#channels.

Conda doesn't interpret the version numbers and all uploads are counted as releases. This then breaks builds https://github.com/conda-forge/great-expectations-feedstock/pull/40 / https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=133887&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7 where it is specified that they require `<3` but the RCs are pulled in as they are in fact `<3`.

**Comment by xhochy** [comment]
Marking them as broken so they no longer interfere: https://github.com/conda-forge/cf-mark-broken/pull/24

**Comment by carlodri** [comment]
Thanks @xhochy! I learned a lot from this issue and your solution!

**Comment by carlodri** [comment]
looks like this can be closed, right?
